name: vakilium
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ^3.9.2

workspace:
  - packages/local_source

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Local packages
  local_source:
    path: packages/local_source/

  # Utilities
  intl: any

  # Network
  thunder: ^0.2.3

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.2

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^17.0.0

  # Dependency injection
  get_it: ^9.0.5
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.10.1
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  melos: ^7.3.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: ru
  arb_dir: lib/src/common/localization
  output_dir: lib/src/common/localization/generated
  use_deferred_loading: false
  line_length: 120

flutter_gen:
  output: lib/src/common/constant/gen
  line_length: 120

  integrations:
    flutter_svg: true

melos:
  name: tv_rain_mobile

  # Define scripts (commands) you can run in your workspace
  scripts:
    # Bootstraps the workspace: installs dependencies and links packages
    boot:
      description: "Install dependencies & link packages for all packages"
      run: melos bootstrap

    # Analyze all Dart/Flutter code
    analyze:
      description: "Run static analysis for all packages"
      run: dart analyze .

    # Clean build artifacts for all packages
    clean:
      description: "Run 'flutter clean' in every package"
      run: melos exec -- flutter clean

    # Format Dart code consistently
    format:
      description: "Format all Dart code to 120 columns"
      run: dart format -l 120 .

    # Build command for production
    build:
      description: "Build release artifacts"
      run: melos run build

    # Bump versions across packages following conventional commits
    version:
      description: "Bump versions & generate CHANGELOG.md"
      run: melos version --conventional-commits --yes

    # Generate code
    gen:
      description: "Generate code"
      run: dart run build_runner build --delete-conflicting-outputs --release

    fluttergen:
      description: "Generate assets with flutter_gen"
      run: dart pub global activate flutter_gen && fluttergen -c pubspec.yaml
